{"uuid": "90fc465a-3566-41bf-a600-8c45d951d8b3", "children": ["32a09fb9-d5fb-469d-add0-c9028ec3eef4", "a2db0ef5-4f5a-4f63-8830-6f89caf0b671", "33476d9b-721c-43b4-90da-1b91429a28ce", "19b2682c-6b5f-44ac-bf29-145436191a88", "c4a3526b-496a-4a80-8e52-14acecf8f068", "080feb84-1220-4ad1-ad92-264cc2703a6f"], "befores": [{"name": "start_wiremock", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: 'docker-compose'\n", "trace": "  File \"/root/.cache/pypoetry/virtualenvs/pytestify-9TtSrW0h-py3.12/lib/python3.12/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/root/.cache/pypoetry/virtualenvs/pytestify-9TtSrW0h-py3.12/lib/python3.12/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"/root/.cache/pypoetry/virtualenvs/pytestify-9TtSrW0h-py3.12/lib/python3.12/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/root/.cache/pypoetry/virtualenvs/pytestify-9TtSrW0h-py3.12/lib/python3.12/site-packages/_pytest/fixtures.py\", line 1139, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/root/.cache/pypoetry/virtualenvs/pytestify-9TtSrW0h-py3.12/lib/python3.12/site-packages/_pytest/fixtures.py\", line 890, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"/Users/ja/IdeaProjects/PyTestify/src/pytestify/tests/conftest.py\", line 47, in start_wiremock\n  File \"/usr/local/lib/python3.12/subprocess.py\", line 548, in run\n    with Popen(*popenargs, **kwargs) as process:\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/subprocess.py\", line 1026, in __init__\n    self._execute_child(args, executable, preexec_fn, close_fds,\n  File \"/usr/local/lib/python3.12/subprocess.py\", line 1955, in _execute_child\n    raise child_exception_type(errno_num, err_msg, err_filename)\n"}, "start": 1725192129966, "stop": 1725192129967}], "start": 1725192129966, "stop": 1725192130796}