{"uuid": "a5e00fb6-8c02-48e4-866a-5b6f5e4ebc2f", "children": ["39e2d84c-1343-4b46-af2d-862eed74f578", "61b4fb2d-7f37-4337-8386-c17433b3069b", "edfcbdcb-b3b4-4820-9076-b4bfa5372a04", "f3cabd1c-4fca-47a2-a968-0acc314f7fd5", "6da10c0b-4665-48fc-9b15-fa07f48c82a3", "2b4ed839-4680-4861-b79b-e1c3095253e7"], "befores": [{"name": "start_wiremock", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: 'docker-compose'\n", "trace": "  File \"/root/.cache/pypoetry/virtualenvs/pytestify-9TtSrW0h-py3.12/lib/python3.12/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/root/.cache/pypoetry/virtualenvs/pytestify-9TtSrW0h-py3.12/lib/python3.12/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"/root/.cache/pypoetry/virtualenvs/pytestify-9TtSrW0h-py3.12/lib/python3.12/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/root/.cache/pypoetry/virtualenvs/pytestify-9TtSrW0h-py3.12/lib/python3.12/site-packages/_pytest/fixtures.py\", line 1139, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/root/.cache/pypoetry/virtualenvs/pytestify-9TtSrW0h-py3.12/lib/python3.12/site-packages/_pytest/fixtures.py\", line 890, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"/Users/ja/IdeaProjects/PyTestify/src/pytestify/tests/conftest.py\", line 47, in start_wiremock\n  File \"/usr/local/lib/python3.12/subprocess.py\", line 548, in run\n    with Popen(*popenargs, **kwargs) as process:\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/subprocess.py\", line 1026, in __init__\n    self._execute_child(args, executable, preexec_fn, close_fds,\n  File \"/usr/local/lib/python3.12/subprocess.py\", line 1955, in _execute_child\n    raise child_exception_type(errno_num, err_msg, err_filename)\n"}, "start": 1725190993497, "stop": 1725190993498}], "start": 1725190993497, "stop": 1725190994230}