{"uuid": "42af41f5-2495-4fba-b6f7-f343a356c61d", "children": ["32662580-c21d-4ad5-b603-21e36b8662e6", "f497543a-9ea4-4ff1-9005-b1431b0075f6", "7efaa22a-36b1-400d-a220-878af00b6915", "b475ea39-32bc-4cb2-9710-0c5d83fa279b", "3d7f6213-74db-4886-9f1b-27fbd872ea91", "5e705180-5da5-4db4-bb94-81380d398911"], "befores": [{"name": "start_wiremock", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: 'docker-compose'\n", "trace": "  File \"/root/.cache/pypoetry/virtualenvs/pytestify-9TtSrW0h-py3.12/lib/python3.12/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/root/.cache/pypoetry/virtualenvs/pytestify-9TtSrW0h-py3.12/lib/python3.12/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"/root/.cache/pypoetry/virtualenvs/pytestify-9TtSrW0h-py3.12/lib/python3.12/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/root/.cache/pypoetry/virtualenvs/pytestify-9TtSrW0h-py3.12/lib/python3.12/site-packages/_pytest/fixtures.py\", line 1139, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/root/.cache/pypoetry/virtualenvs/pytestify-9TtSrW0h-py3.12/lib/python3.12/site-packages/_pytest/fixtures.py\", line 890, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"/Users/ja/IdeaProjects/PyTestify/src/pytestify/tests/conftest.py\", line 47, in start_wiremock\n  File \"/usr/local/lib/python3.12/subprocess.py\", line 548, in run\n    with Popen(*popenargs, **kwargs) as process:\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/subprocess.py\", line 1026, in __init__\n    self._execute_child(args, executable, preexec_fn, close_fds,\n  File \"/usr/local/lib/python3.12/subprocess.py\", line 1955, in _execute_child\n    raise child_exception_type(errno_num, err_msg, err_filename)\n"}, "start": 1725191653930, "stop": 1725191653931}], "start": 1725191653930, "stop": 1725191654621}