INFO:pytestify.client.api_client:Initialized APIClient with base URL: http://localhost:8080
DEBUG:pytestify.client.api_client:Created URL: http://localhost:8080/posts
INFO:pytestify.client.api_client:Performing POST request to http://localhost:8080/posts with data: None and json: {'title': 'foo', 'body': 'bar'}
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost:8080
DEBUG:urllib3.connectionpool:http://localhost:8080 "POST /posts HTTP/11" 404 None
WARNING:root:Request failed: 404 Client Error: Not Found for url: http://localhost:8080/posts. Retrying... (1/3)
DEBUG:urllib3.connectionpool:http://localhost:8080 "POST /posts HTTP/11" 404 None
WARNING:root:Request failed: 404 Client Error: Not Found for url: http://localhost:8080/posts. Retrying... (2/3)
DEBUG:urllib3.connectionpool:http://localhost:8080 "POST /posts HTTP/11" 404 None
WARNING:root:Request failed: 404 Client Error: Not Found for url: http://localhost:8080/posts. Retrying... (3/3)
CRITICAL:root:Request failed after 3 attempts.
ERROR:pytestify.client.api_client:POST request to http://localhost:8080/posts failed and returned None
INFO:pytestify.client.api_client:Closed APIClient session
